// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.AppConfig>;

export function GetDiff():Promise<Array<main.DiffItem>>;

export function GetRecommendations():Promise<Array<main.RecItem>>;

export function GetSkills(arg1:string,arg2:string,arg3:string):Promise<Array<main.SkillInfo>>;

export function GetStatus():Promise<main.AppStatus>;

export function GetTools():Promise<Array<main.ToolInfo>>;

export function Pull():Promise<main.PullResult>;

export function Push():Promise<main.PushResult>;

export function SaveConfig(arg1:string,arg2:string):Promise<void>;

export function ShowDialog(arg1:string,arg2:string):Promise<void>;
