// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDiff() {
  return window['go']['main']['App']['GetDiff']();
}

export function GetRecommendations() {
  return window['go']['main']['App']['GetRecommendations']();
}

export function GetSkills(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSkills'](arg1, arg2, arg3);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTools() {
  return window['go']['main']['App']['GetTools']();
}

export function Pull() {
  return window['go']['main']['App']['Pull']();
}

export function Push() {
  return window['go']['main']['App']['Push']();
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function ShowDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowDialog'](arg1, arg2);
}
